version: 2
registries:
  git-gitlab-com:
    type: git
    url: https://gitlab.com
    username: thecampagnards
    password: "${{secrets.GIT_GITLAB_COM_PASSWORD}}"

updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  registries:
  - git-gitlab-com
